### ISSUE TITLE
TODO 

### ISSUE THREAD

**Issue by dangub86** [prima-s/onlus-manager-test#5]
**TODO**

- [x] Prova inserimento socio (da frontend a db)

- [ ] Prova Login come amministratore

- [ ] Aggiunta Spring Security

**Comment by dangub86** [comment]
Prova inserimento socio funzionante (per il momento senza hibernate) ma restano da sistemare: 
 - la gestione del campo 'scadenzaTessera' (da gestire in automatico lato backend settandola direttamente al termine dell'anno corrente e facendo attenzione al formato in modo che non crei problemi nella conversione al Date di mysql); 
 - l'aggiunta lato backend e frontend del ruolo( o più ruoli) da assegnare al nuovo socio creato;
- l'implementazione delle credenziali e della creazione delle stesse al momento dell'inserimento nel db del nuovo socio;
